#!/bin/sh

########################################################################
# CHANGE THE FOLLOWING FOR YOUR SETUP !!! 
#
# If gnome is installed in /usr/local you shouldn't have to change much.
# Just make sure theat LIBINTLDIR points to a directory with a copy of
# libintl.a in it.
########################################################################

# GNOME PREFIX
GNOMEPREFIX=/usr/local

# Where is gnomeConf.sh
GNOMECONFIGSH=${GNOMEPREFIX}/lib/gnomeConf.sh

# Define location of libintl, and libintl's locale dir
GNOMELOCALEDIR=\""${GNOMEPREFIX}/share/locale"\"
LIBINTLDIR=-L../intl
GNOMEPIXMAPDIR=\""${GNOMEPREFIX}/share/pixmaps"\"

# Sorry, I am special (ignore this stuff, it should be commented)
# echo "DOH! Forgot to comment out Scott's local config -- *EDIT Build file*"
# GNOMELOCALEDIR=\""/usr/people/sdh/gnome/share/locale"\"
# GNOMECONFIGSH=/share/sdh/gnome/lib/gnomeConf.sh 

# Adjust CFLAGS here if desired
CFLAGS="${CFLAGS} -O2 -DGNOMELOCALEDIR=${GNOMELOCALEDIR}"

########################################################################
# STOP EDITING HERE (unless you need to adjust -lcurses) 
########################################################################

source ${GNOMECONFIGSH}

# Is there a config.h in the next dir up?
if [ -f ../config.h ] ; then
    CFLAGS="${CFLAGS} -I../"
else
    echo "#define PACKAGE \"gnome-games\"" > config.h
    echo "#define VERSION \"980621\"" >> config.h
    CFLAGS="${CFLAGS} -I./"
fi

# GNOME sources
GOBS="clist.c yahtzee.c computer.c gyahtzee.c  setup.c"

# CURSES sources
COBS="cyahtzee.c scores.c yahtzee.c computer.c"

echo ""

echo "**********************************************************************"
echo "* To add entries to the gnome panel for gyahtzee, DO THIS BY HAND    *"
echo "*   cp gnome.desktop \${GNOMEPREFIX}/share/apps/Games/               *" 
echo "*   cp pix/gnome-gyahtzee.png \${GNOMEPREFIX}/share/pixmaps          *"
echo "**********************************************************************"

echo ""

echo Compiling and linking Gnome version . . . \(this is slow\)
echo gcc -o gyahtzee ${CFLAGS} ${GNOME_INCLUDEDIR} ${GOBS} \
	${GNOME_LIBDIR} ${GNOMEUI_LIBS} ${LIBINTLDIR} -lintl
gcc -o gyahtzee ${CFLAGS} ${GNOME_INCLUDEDIR} ${GOBS} \
	${GNOME_LIBDIR} ${GNOMEUI_LIBS} ${LIBINTLDIR} -lintl

echo ""
echo If you just want the Gnome version, you can break/abort anytime now.
echo ""

echo Compiling and linking NCurses version . . . \(this too is slow\)
# Still need all the gnomeincludes because libintl includes are hidden
# somewhere in gnome.h.
echo gcc -o cyahtzee ${CFLAGS} ${GNOME_INCLUDEDIR} ${COBS} \
	${LIBINTLDIR}  -lintl -lncurses
gcc -o cyahtzee ${CFLAGS} ${GNOME_INCLUDEDIR} ${COBS} \
	${LIBINTLDIR}  -lintl -lncurses


